### PR TITLE
Add split workflow, allowing the action to be used in PRs created from forks

### LINKED ISSUE #49: Error posting comments about code from forks
When an outside contributor makes a PR, clang-tidy can review the code but it can't post comments due to a lack of permissions.

The way GitHub Actions is set up is that forks have very limited permissions, including the inability to access any repository or organization secrets you've set up with extra permissions.

I see two ways of solving this:
1) Making the action running this unsafe by using pull_request_target - this would mean that the person creating the fork & PR have access to your secrets with their modified code, which means they could easily abuse or leak the secrets so this is not viable for public repositories.
2) Splitting the action up into two parts. The unprivileged action that runs clang-tidy, parses errors/warnings etc and adds them to `::set-output`, and the privileged action that parses the output set from the first action and posts the actual PR comments. (Similar to the example [posted here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/))

I would be interested in implementing 2), but I'd like to hear your thoughts about before I do any development in case I've missed something obvious or if you feel some part of the solution wouldn't fit into this action.

<details>
  <summary>Example logs from the error occurring: (click to expand)</summary>

```
2022-07-31T20:20:45.0448070Z ##[group]Run ZedThree/clang-tidy-review@v0.8.4
2022-07-31T20:20:45.0448519Z with:
2022-07-31T20:20:45.0448686Z   build_dir: build
2022-07-31T20:20:45.0448889Z   config_file: .clang-tidy
2022-07-31T20:20:45.0449243Z   token: ***
2022-07-31T20:20:45.0449496Z   base_dir: /home/runner/work/chatterino2/chatterino2
2022-07-31T20:20:45.0449740Z   clang_tidy_version: 12
2022-07-31T20:20:45.0450087Z   clang_tidy_checks: -*,performance-*,readability-*,bugprone-*,clang-analyzer-*,cppcoreguidelines-*,mpi-*,misc-*
2022-07-31T20:20:45.0450427Z   include: *.[ch],*.[ch]xx,*.[ch]pp,*.[ch]++,*.cc,*.hh
2022-07-31T20:20:45.0450655Z   max_comments: 25
2022-07-31T20:20:45.0450841Z   pr: 3886
2022-07-31T20:20:45.0451037Z   repo: Chatterino/chatterino2
2022-07-31T20:20:45.0451258Z env:
2022-07-31T20:20:45.0451490Z   pythonLocation: /opt/hostedtoolcache/Python/3.10.5/x64
2022-07-31T20:20:45.0451906Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.5/x64/lib:/home/runner/work/chatterino2/chatterino2/qt/Qt/5.15.2/gcc_64/lib
2022-07-31T20:20:45.0452312Z   PKG_CONFIG_PATH: /home/runner/work/chatterino2/chatterino2/qt/Qt/5.15.2/gcc_64/lib/pkgconfig
2022-07-31T20:20:45.0452977Z   Qt5_Dir: /home/runner/work/chatterino2/chatterino2/qt/Qt/5.15.2/gcc_64
2022-07-31T20:20:45.0453429Z   Qt5_DIR: /home/runner/work/chatterino2/chatterino2/qt/Qt/5.15.2/gcc_64
2022-07-31T20:20:45.0453736Z   QT_PLUGIN_PATH: /home/runner/work/chatterino2/chatterino2/qt/Qt/5.15.2/gcc_64/plugins
2022-07-31T20:20:45.0454058Z   QML2_IMPORT_PATH: /home/runner/work/chatterino2/chatterino2/qt/Qt/5.15.2/gcc_64/qml
2022-07-31T20:20:45.0454303Z ##[endgroup]
2022-07-31T20:20:45.0834749Z ##[command]/usr/bin/docker run --name cd98f5e81d1ff62384aabaebb014676eef0ab_833c71 --label 4cd98f --workdir /github/workspace --rm -e pythonLocation -e LD_LIBRARY_PATH -e PKG_CONFIG_PATH -e Qt5_Dir -e Qt5_DIR -e QT_PLUGIN_PATH -e QML2_IMPORT_PATH -e INPUT_BUILD_DIR -e INPUT_CONFIG_FILE -e INPUT_TOKEN -e INPUT_BASE_DIR -e INPUT_CLANG_TIDY_VERSION -e INPUT_CLANG_TIDY_CHECKS -e INPUT_INCLUDE -e INPUT_EXCLUDE -e INPUT_APT_PACKAGES -e INPUT_CMAKE_COMMAND -e INPUT_MAX_COMMENTS -e INPUT_PR -e INPUT_REPO -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/chatterino2/chatterino2":"/github/workspace" 4cd98f:5e81d1ff62384aabaebb014676eef0ab  "--clang_tidy_binary=clang-tidy-12" "--token=***" "--repo=Chatterino/chatterino2" "--pr=3886" "--build_dir=build" "--base_dir=/home/runner/work/chatterino2/chatterino2" "--clang_tidy_checks=-*,performance-*,readability-*,bugprone-*,clang-analyzer-*,cppcoreguidelines-*,mpi-*,misc-*" "--config_file=.clang-tidy" "--include='*.[ch],*.[ch]xx,*.[ch]pp,*.[ch]++,*.cc,*.hh'" "--exclude=''" "--apt-packages=" "--cmake-command=''"
2022-07-31T20:20:45.8627385Z Found 'build/compile_commands.json', updating absolute paths
2022-07-31T20:20:45.8628286Z Replacing '/home/runner/work/chatterino2/chatterino2' with '/github/workspace'
2022-07-31T20:20:46.7076671Z 
2022-07-31T20:20:46.7077060Z Diff from GitHub PR:
2022-07-31T20:20:46.7077901Z [<PatchedFile: CHANGELOG.md>, <PatchedFile: src/singletons/helper/GifTimer.cpp>, <PatchedFile: src/singletons/helper/GifTimer.hpp>]
2022-07-31T20:20:46.7078240Z 
2022-07-31T20:20:46.7078356Z include: *.[ch], file list now: []
2022-07-31T20:20:46.7078622Z include: *.[ch]xx, file list now: []
2022-07-31T20:20:46.7079484Z include: *.[ch]pp, file list now: ['src/singletons/helper/GifTimer.cpp', 'src/singletons/helper/GifTimer.hpp']
2022-07-31T20:20:46.7080044Z include: *.[ch]++, file list now: ['src/singletons/helper/GifTimer.cpp', 'src/singletons/helper/GifTimer.hpp']
2022-07-31T20:20:46.7080772Z include: *.cc, file list now: ['src/singletons/helper/GifTimer.cpp', 'src/singletons/helper/GifTimer.hpp']
2022-07-31T20:20:46.7081316Z include: *.hh, file list now: ['src/singletons/helper/GifTimer.cpp', 'src/singletons/helper/GifTimer.hpp']
2022-07-31T20:20:46.7081847Z exclude: , file list now: ['src/singletons/helper/GifTimer.cpp', 'src/singletons/helper/GifTimer.hpp']
2022-07-31T20:20:46.7082563Z Checking these files: ['src/singletons/helper/GifTimer.cpp', 'src/singletons/helper/GifTimer.hpp']
2022-07-31T20:20:46.7087788Z Line filter for clang-tidy:
2022-07-31T20:20:46.7088325Z ["{'name': 'src/singletons/helper/GifTimer.cpp', 'lines': [[11, 11]]}","{'name': 'src/singletons/helper/GifTimer.hpp', 'lines': [[8, 8]]}"]
2022-07-31T20:20:46.7088786Z 
2022-07-31T20:20:46.7088953Z Using config: -config-file=.clang-tidy
2022-07-31T20:20:46.7089646Z ##[group]Running:
2022-07-31T20:20:46.7090479Z 	clang-tidy-12 -p=build -config-file=.clang-tidy -line-filter=["{'name': 'src/singletons/helper/GifTimer.cpp', 'lines': [[11, 11]]}","{'name': 'src/singletons/helper/GifTimer.hpp', 'lines': [[8, 8]]}"] src/singletons/helper/GifTimer.cpp src/singletons/helper/GifTimer.hpp --export-fixes=clang_tidy_review.yaml
2022-07-31T20:21:16.7796055Z ##[endgroup]
2022-07-31T20:21:16.7843853Z 
2022-07-31T20:21:16.7843860Z 
2022-07-31T20:21:16.7844513Z clang-tidy failed with return code 1 and error:
2022-07-31T20:21:16.7844819Z 108928 warnings and 1 error generated.
2022-07-31T20:21:16.7845185Z Error while processing /github/workspace/src/singletons/helper/GifTimer.cpp.
2022-07-31T20:21:16.7845521Z 194107 warnings and 1 error generated.
2022-07-31T20:21:16.7845857Z Error while processing /github/workspace/src/singletons/helper/GifTimer.hpp.
2022-07-31T20:21:16.7846334Z Suppressed 194106 warnings (194099 in non-user code, 7 due to line filter).
2022-07-31T20:21:16.7846935Z Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
2022-07-31T20:21:16.7847820Z Found compiler error(s).
2022-07-31T20:21:16.7847960Z 
2022-07-31T20:21:16.7848040Z Output was:
2022-07-31T20:21:16.7848514Z /github/workspace/src/common/SignalVector.hpp:5:10: error: 'boost/noncopyable.hpp' file not found [clang-diagnostic-error]
2022-07-31T20:21:16.7849075Z #include <boost/noncopyable.hpp>
2022-07-31T20:21:16.7849290Z          ^
2022-07-31T20:21:16.7849865Z /github/workspace/src/singletons/helper/GifTimer.hpp:8:25: warning: invalid case style for global variable 'gifFrameLength' [readability-identifier-naming]
2022-07-31T20:21:16.7850313Z constexpr long unsigned gifFrameLength = 20;
2022-07-31T20:21:16.7850574Z                         ^~~~~~~~~~~~~~
2022-07-31T20:21:16.7850806Z                         GIF_FRAME_LENGTH
2022-07-31T20:21:16.7850956Z 
2022-07-31T20:21:16.7851042Z Took: 0:00:30.071182
2022-07-31T20:21:16.7851339Z clang-tidy had the following warnings:
2022-07-31T20:21:16.7853910Z  {'MainSourceFile': '/github/workspace/src/singletons/helper/GifTimer.cpp', 'Diagnostics': [{'DiagnosticName': 'clang-diagnostic-error', 'DiagnosticMessage': {'Message': "'boost/noncopyable.hpp' file not found", 'FilePath': '/github/workspace/src/common/SignalVector.hpp', 'FileOffset': 71, 'Replacements': []}, 'Level': 'Error', 'BuildDirectory': '/github/workspace/build/src', 'Ranges': [{'FilePath': '/github/workspace/src/common/SignalVector.hpp', 'FileOffset': 71, 'Length': 23}]}, {'DiagnosticName': 'readability-identifier-naming', 'DiagnosticMessage': {'Message': "invalid case style for global variable 'gifFrameLength'", 'FilePath': '/github/workspace/src/singletons/helper/GifTimer.hpp', 'FileOffset': 119, 'Replacements': [{'FilePath': '/github/workspace/src/singletons/helper/GifTimer.hpp', 'Offset': 119, 'Length': 14, 'ReplacementText': 'GIF_FRAME_LENGTH'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src'}]}
2022-07-31T20:21:16.7860688Z ##[group]Creating review from warnings
2022-07-31T20:21:16.7861297Z {'Message': "'boost/noncopyable.hpp' file not found", 'FilePath': '/github/workspace/src/common/SignalVector.hpp', 'FileOffset': 71, 'Replacements': []}
2022-07-31T20:21:16.7861820Z     line_num=4;    line_offset=9;    source_line='#include <boost/noncopyable.hpp>'
2022-07-31T20:21:16.7862061Z     
2022-07-31T20:21:16.7862465Z WARNING: Skipping comment for file 'src/common/SignalVector.hpp' not in PR changeset. Comment body is:
2022-07-31T20:21:16.7862933Z warning: 'boost/noncopyable.hpp' file not found [clang-diagnostic-error]
2022-07-31T20:21:16.7863210Z ```cpp
2022-07-31T20:21:16.7863423Z #include <boost/noncopyable.hpp>
2022-07-31T20:21:16.7863635Z          ^
2022-07-31T20:21:16.7863793Z ```
2022-07-31T20:21:16.7863897Z 
2022-07-31T20:21:16.7865036Z {'Message': "invalid case style for global variable 'gifFrameLength'", 'FilePath': '/github/workspace/src/singletons/helper/GifTimer.hpp', 'FileOffset': 119, 'Replacements': [{'FilePath': '/github/workspace/src/singletons/helper/GifTimer.hpp', 'Offset': 119, 'Length': 14, 'ReplacementText': 'GIF_FRAME_LENGTH'}]}
2022-07-31T20:21:16.7866177Z     line_num=7;    line_offset=24;    source_line='constexpr long unsigned gifFrameLength = 20;'
2022-07-31T20:21:16.7866498Z     
2022-07-31T20:21:16.7866743Z ----------
2022-07-31T20:21:16.7867117Z old_line='constexpr long unsigned gifFrameLength = 20;'
2022-07-31T20:21:16.7867558Z new_line='constexpr long unsigned GIF_FRAME_LENGTH = 20;'
2022-07-31T20:21:16.7867865Z ----------
2022-07-31T20:21:16.7868800Z ##[endgroup]
2022-07-31T20:21:16.7869013Z Created the following review:
2022-07-31T20:21:16.7869330Z  {'body': 'clang-tidy made some suggestions',
2022-07-31T20:21:16.7869809Z  'comments': [{'body': "warning: invalid case style for global variable 'gifFrameLength' [readability-identifier-naming]\n"
2022-07-31T20:21:16.7870186Z                        '\n'
2022-07-31T20:21:16.7870449Z                        '```suggestion\n'
2022-07-31T20:21:16.7870792Z                        'constexpr long unsigned GIF_FRAME_LENGTH = 20;\n'
2022-07-31T20:21:16.7871091Z                        '```\n',
2022-07-31T20:21:16.7871329Z                'line': 8,
2022-07-31T20:21:16.7871632Z                'path': 'src/singletons/helper/GifTimer.hpp',
2022-07-31T20:21:16.7871933Z                'side': 'RIGHT'}],
2022-07-31T20:21:16.7872178Z  'event': 'COMMENT'}
2022-07-31T20:21:16.7872410Z Removing already posted or extra comments
2022-07-31T20:21:16.9058447Z Posting the review:
2022-07-31T20:21:16.9058849Z  {'body': 'clang-tidy made some suggestions',
2022-07-31T20:21:16.9059292Z  'comments': [{'body': 'warning: invalid case style for global variable '
2022-07-31T20:21:16.9059930Z                        "'gifFrameLength' [readability-identifier-naming]\n"
2022-07-31T20:21:16.9060279Z                        '\n'
2022-07-31T20:21:16.9060567Z                        '```suggestion\n'
2022-07-31T20:21:16.9060957Z                        'constexpr long unsigned GIF_FRAME_LENGTH = 20;\n'
2022-07-31T20:21:16.9061268Z                        '```\n',
2022-07-31T20:21:16.9061713Z                'line': 8,
2022-07-31T20:21:16.9062075Z                'path': 'src/singletons/helper/GifTimer.hpp',
2022-07-31T20:21:16.9062413Z                'side': 'RIGHT'}],
2022-07-31T20:21:16.9062688Z  'event': 'COMMENT'}
2022-07-31T20:21:17.1406031Z {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-review-for-a-pull-request"}
2022-07-31T20:21:17.1414461Z Traceback (most recent call last):
2022-07-31T20:21:17.1414984Z   File "/review.py", line 810, in <module>
2022-07-31T20:21:17.1415247Z     main(
2022-07-31T20:21:17.1415468Z   File "/review.py", line 676, in main
2022-07-31T20:21:17.1415728Z     pull_request.post_review(trimmed_review)
2022-07-31T20:21:17.1416020Z   File "/review.py", line 115, in post_review
2022-07-31T20:21:17.1416308Z     post_review_response.raise_for_status()
2022-07-31T20:21:17.1417027Z   File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 1021, in raise_for_status
2022-07-31T20:21:17.1417401Z     raise HTTPError(http_error_msg, response=self)
2022-07-31T20:21:17.1417868Z requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/Chatterino/chatterino2/pulls/3886/reviews
```
</details>

### PR DESCRIPTION
**Pull request by pajlada**
## Why `python:3` docker base image?

For the `post_comments` workflow, I've decided to use the `python:3` docker image from dockerhub.
This image is based off of debian.
Because no system binaries are run other than python, I don't expect any issues with the Ubuntu <-> Debian jump. Being able to skip any `apt` calls speeds up the workflow by a good chunk.

## What's changed

A lot of the code from `review.py` has been moved to a package `clang_tidy_review` stored in the path `/post_comments/clang_tidy_review` - this is to ensure the package can be used by both the review and post_comments workflows.

The main workflow Dockerfile has been updated to include the `post_comments` directory, this is done to include the shared library contained within that directory

The main workflow has a new input: `post_comments`.  
This input controls whether comments should be posted by this workflow or not.  
**Action item: Does this input name accurately describe its functionality?**

 - [x] Make the split workflow work with forks
 - [x] Post an error annotation if the regular workflow is used with a link to the "How to use the split workflow" page
 - [x] Add a section to the main `README.md` page to describe how and why to use the split workflow

Fixes #49

Example PR showing the error annotation: https://github.com/pajlads/test-cpp-project/pull/2 - it's not showing up straight in the PR page because it's not linked to a file, rather you need to click details on the failed action. If this is something we very much want we could potentially use the first file from the review that was about to be posted to have it show up more like a PR comment

This PR is hefty, and contains a lot of different things done in the same PR. I'd suggest this is either squash & merged, or let me know and I'll clean up the commits to more manageable pieces before it gets merged in.

Looking forward to hear your feedback!

To test this right now, you can point your action at my fork like done in my [test project](https://github.com/pajlada/mini-cpp-project): https://github.com/pajlada/mini-cpp-project/blob/master/.github/workflows/build.yml and https://github.com/pajlada/mini-cpp-project/blob/master/.github/workflows/post_comments.yml

The downloading and uploading of artifacts could be done by just using the raw github api using the requests library, which would make it a lot cleaner to use the split workflow.

### CODE REVIEW

**Comment by pajlada** [comment]
@FlorianReimold This is now in a workable state, I've confirmed this works in a way that would work for me in my projects that get a lot of pull requests from forks.

How it's actually implemented right now with a mix of other github-script actions and what-not is not really how I envision it looking when this PR gets its final polish, but it's ready to be played with at least!

**Comment by FlorianReimold** [comment]
@pajlada: Thanks for this gigantic PR! I am going to test out your clang-tidy-review version as soon as possible and report back in the next days!

**Comment by FlorianReimold** [comment]
I gave it a rough test. It worked. I would totally use it in the exact state it is in.

What I still have noticed:
- There is no LGTM comment anymore. This is a little inconsistent, but honestly, I don’t miss it at all. It never provided a real value, only spammed everybody with notifications and emails.
- The number of comments isn’t set any more, so you cannot “fail” the main clang-tidy-review workflow anymore if clang-tidy has detected issues
- The Post-comments script is always taken from master. I worked on two temporary branches first and the clang-tidy-review action would work, but the post-comments action would not trigger at all. It started working when I pushed the actions to master.
- The Post clang-tidy review action fails, whenever clang-tidy-review didn’t detect any issue, as the workflow cannot download the file. This clutters the overall appearance of the Actions tab, as every success (no clang-tidy findings) is accompanied by a failed post-comments workflow. 
- The readme.md should be adapted. Currently it contains an example for clang-tidy-review@0.7 😉

**Comment by ZedThree** [comment]
Thanks @pajlada for this, and also @FlorianReimold for testing it!

Florian's second point is quite important -- some people like to use the action as pass/fail rather than just comments, so it's important to get that working.

My main suggestion is to undo the move of `post_comments` out of review, and instead have the main action always create the comments as a JSON file and upload _that_ as an artefact. Then, the second `post_comments` action could be a javascript action instead of docker. That would have a couple of advantages:

1. it would be much faster as it wouldn't need to build or even download the docker container
2. it could incorporate downloading the comments json artefact so the user would only need a single step in their workflow yaml file.

Admittedly it would involve writing some javascript, but it should just be able to use the [github octokit library](https://octokit.github.io/rest.js/v18#pulls-create-review-comment) to upload the comments straight from the json file

**Comment by pajlada** [comment]
Thank for your feedback folks!

I will look to make the requested changes this weekend and add some overall polish

Non-exhaustive list for myself:
 - [ ] Update/review README.md examples
 - [ ] Fix LGTM comment
 - [ ] Ensure output `total_comments` is correctly output from both actions, regardless of `post_comments` input value
 - [ ] Explore javascript/octokit `post_comments` action

**Comment by FlorianReimold** [comment]
Just to give you my opinion on the javascript post-comments workflow: Honestly, I wouldn't care too much about that. The current python3-docker based version completes in about 60 seconds, which is totally reasonable. (_Also I don't know javascript 😉_)

Example run: https://github.com/FlorianReimold/ecal-test-snapshot/actions/runs/2868416302

**Comment by pajlada** [comment]
To begin, sorry for the big PR! After 49 force pushes I believe I've done all I can to make it as easy to review as possible. It's now in a state that I'm happy with, so I believe there's just a few things left.

What I have **not** done, is convert the `post_comments` child action to javascript yet. This can still be done, however, as is now a bit easier to see, the javascript action would need to duplicate quite a lot of logic, namely:
 - Searching for previous comments
 - Limiting the amount of comments to make
 - The LGTM comment posting logic (find last comment, skip posting LGTM if last comment was LGTM (which is broken now btw but not in scope of this PR to fix))

The workflow necessary to download/upload the artifact is still ugly right now, but this can be improved in python by making REST API requests ourselves (not relying on PyGithub)

Questions:
1. Do you still want the `post_comments` child action converted to javascript?
2. If no to _1._, do you want the workflow cleanup as part of this pull request or as another pull request?
3. Naming! I've come to dislike the name of the action and option `post_comments`. I think the name should instead be `post_review` as that's what it's doing. Thoughts?

**Comment by FlorianReimold** [comment]
> 3\. Naming! I've come to dislike the name of the action and option `post_comments`. I think the name should instead be `post_review` as that's what it's doing. Thoughts?

First of all I would also prefer `post_reviews`, as that is more in line with what it actually does. When I applied the previous dev version I however found it a little counterintuitive to set "post_comments=false" in order to get the two-step-workflow working - I mean I actually want it to post comments, but from another workflow. I don't really have a better name for it though. Maybe "use_split_workflow=true" or something like that...

**Comment by pajlada** [comment]
> > 3. Naming! I've come to dislike the name of the action and option `post_comments`. I think the name should instead be `post_review` as that's what it's doing. Thoughts?
> 
> First of all I would also prefer `post_reviews`, as that is more in line with what it actually does. When I applied the previous dev version I however found it a little counterintuitive to set "post_comments=false" in order to get the two-step-workflow working - I mean I actually want it to post comments, but from another workflow. I don't really have a better name for it though. Maybe "use_split_workflow=true" or something like that...

I like that naming idea a lot, makes it more of a conscious choice in my head that you are going to be using the action in an entirely different way

**Comment by ZedThree** [comment]
+1 for `split_workflow` :slightly_smiling_face: 

Leaving the workflow as Python for now seems like the sensible way forward, and maybe I'll look at converting it to javascript in future

**Comment by pajlada** [comment]
> Hey everybody, we don't want this PR to die, right? blush I am currently using an [old fork](https://github.com/FlorianReimold/clang-tidy-review/tree/feat/split-up-review-and-post-workflows?rgh-link-date=2022-09-19T07%3A59%3A37Z) in our main repository and it works perfectly (OK, well, there is an issue, but it has nothing to do with the split workflow). The fork is at the state when I tried it out last time.
> 
> Are we waiting for me to approve the current workflow again? I can try it out and see if I find issues or room for improvements! +1

I've been a bit busy on other work recently, I think this PR is in a pretty good state and I've been testing it with pull requests in [this repo](https://github.com/Chatterino/chatterino2/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)

It runs into some undiscoverable issues sometimes where the split workflow fails because the artifact uploading failed - I'm not sure how this could be made more discoverable, but it could be handled better.

The workflows I'm running now:
1. Build https://github.com/Chatterino/chatterino2/blob/master/.github/workflows/build.yml#L149-L164
2. Post review https://github.com/Chatterino/chatterino2/blob/master/.github/workflows/post-clang-tidy-review.yml

**Comment by ZedThree** [comment]
I'm very busy this week, but I'll try and have a proper look when I can

**Comment by FlorianReimold** [comment]
> It runs into some undiscoverable issues sometimes where the split workflow fails because the artifact uploading failed - I'm not sure how this could be made more discoverable, but it could be handled better.

Hm maybe you could just always create a file, even if it is empty? The download should then more or less never fail, just because there should always be a file present 🤔

**Review by ZedThree — APPROVED** [review]

**Comment by ZedThree** [comment]
Thanks @pajlada and @FlorianReimold for writing and testing this! I haven't yet found a good way of testing this Action except manually, so I really appreciate the effort you've both put in. I'm going to merge this now so that other people can start using it.

**Comment by ZedThree** [comment]
You can use this now in v0.10.0

**Pull request merged**
