### PR TITLE
Add option to edit LGTM message and to turn it off

### PR DESCRIPTION
**Pull request by bwrsandman**
Implements #47

- [x] Add description about empty string skipping LGTM message
- [x] Test empty message
- [x] Test Custom message
- [x] Test with default message

### CODE REVIEW

**Comment by ZedThree** [comment]
Thanks @bwrsandman! I take it setting it to the empty string means the comment doesn't get posted -- does it need an explicit check, or does GitHub automatically reject empty comments?

**Comment by bwrsandman** [comment]
There is an explicit check. I'm currently testing it it works here:
https://github.com/openblack/openblack/pull/526
https://github.com/openblack/openblack/pull/527

**Comment by ZedThree** [comment]
Ah, I missed that, sorry! Hadn't had enough caffeine :)

Would you mind just noting in the description that setting it to the empty string turns off the comment?

If you're happy this works for your case, I'll merge it

**Comment by bwrsandman** [comment]
Not sure why but it posts empty quotes...
https://github.com/openblack/openblack/pull/527#issuecomment-1201154446

**Comment by ZedThree** [comment]
Because we're passing the arguments through Github's YAML, then Docker, then bash, it's quite possible it's getting passed through as `"''"`. I had something like that before, so there's a `strip_enclosing_quotes` function that makes sure all the quotes are removed. Then we should end up with an actual empty string and the `not body` conditional should trigger.

**Comment by bwrsandman** [comment]
I've tested and added the part about disabling the comment.

**Review by ZedThree — APPROVED** [review]
Awesome, thanks @bwrsandman !

**Pull request merged**
